### PR TITLE
Seraph branch

### PR DESCRIPTION
**Pull request by seraph776**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/Tenet-Coding/ArtofCoding/blob/main/CONTRIBUTING.md#pull-requests)?

- Yes

### Description

- #30 
- Updated `README.md` file to include code title, and link to code. 
- Adding `valid_palindrome.py` including `unittest`

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
- N/A

### CODE REVIEW

**Review by Harshil-Jani — CHANGES_REQUESTED** [review]
Ah ! There seems to be a spelling error with your filename ! Please fix that and then we are good to go . Change `valid_palidrome.py` to `valid_palindrome.py`.

**Review by Harshil-Jani — APPROVED** [review]

**Comment by seraph776** [comment]
Thank you!

**Comment by Harshil-Jani** [comment]
@seraph776 The Deep Source workflow is failing ! Can you please do the suggested changes ? Let me know If you can't understand what you need to do.
Check this out : 
https://deepsource.io/gh/Tenet-Coding/ArtofCoding/run/26c484e0-cffd-4ff0-9c7b-e020ef9c8caf/python/

Basically, Your Comments are flowing beyond word limit.  Try to limit those and use new line after 88 chars.
Also, The comment formatting must be as below
image

**Comment by seraph776** [comment]
Hi @Harshil-Jani ,

No worries. I made the recommended changes suggested by Deep Source.  Let me know if there is anything else I can do - Thanks!

**Comment by Harshil-Jani** [comment]
@seraph776 Ah ! The errors still persists. I would suggest instead of you manually changing the file. Try some code linter 
For example use Black

`pip install black`
and then go to the directory where your file exists and run command
`black valid_palindrome.py`

Not sure if it is compatible with deepsource but we can give this a try.

**Comment by seraph776** [comment]
@Harshil-Jani, any luck this round?

**Comment by Harshil-Jani** [comment]
I have fixed the extra deepsource errors ! Thankyou @seraph776 for contributing.

**Comment by seraph776** [comment]
@Harshil-Jani Thanks!

**Pull request merged**
